package: com.fleet.products
imports:
  - com.fleet.common
  - com.fleet.system
  - com.fleet.versions
types:
  objects:
    Product:
      docs: |
        Products are the individual assets to be deployed to the deployment (ship)
      builder: true
      fields:
        frn: common.ProductFrn
        name: string
        namespace: string
        createdAt: datetime
        modifiedAt: datetime
        environment: system.Environment
        versions: map<string, common.VersionFrn>
    CreateProductRequest:
      fields:
        name: string
        namespace: optional<string>
        environment: system.Environment
    ListProductResponse:
      builder: true
      fields:
        count: int
        total: int
        items: list<Product>
    GetProductResponse:
      builder: true
      fields:
        product: Product
        versions: list<versions.Version>        

services:
  ProductService:
    base-path: /api/v1/products
    endpoints:
      listProducts:
        http: GET /
        docs: list all products
        args:
          query: 
            offset: optional<long>
            pageSize: optional<long>
        returns: ListProductResponse
      createProduct:
        http: POST /
        docs: creates a new product
        args:
          body: CreateProductRequest
        returns: Product
      getProduct:
        http: GET /{productFrn}
        docs: get single product
        args:
          path:
            productFrn: string
          query:
            expandVersions: optional<boolean>
        returns: GetProductResponse
      addVersion:
        http: POST /{productFrn}/versions
        docs: add new version of product
        args:
          path:
            productFrn: string
          body: versions.CreateVersionRequest
        returns: versions.Version
