package: com.fleet.products
imports:
  - com.fleet.common
types:
  objects:
    Product:
      docs: |
        Products are the individual assets to be deployed to the deployment (ship)
      builder: true
      fields:
        frn: common.ProductFrn
        name: string
        namespace: string
        createdAt: datetime
        modifiedAt: datetime
    CreateProductRequest:
      fields:
        name: string
        namespace: optional<string>

services:
  ProductService:
    base-path: /api/v1/products
    endpoints:
      listProducts:
        http: GET /
        docs: list all products
        returns: list<Product>
      getProduct:
        http: GET /{productFrn}
        docs: get single product
        args:
          path:
            productFrn: string
        returns: Product
      createProduct:
        http: POST /
        docs: creates a new product
        args:
          body: CreateProductRequest
        returns: Product